//
// Created by xenon on 20.05.17.
//

#ifndef ENUM_OR_STR
#define ENUM_OR_STR(x)
#endif

ENUM_OR_STR(ETT_PLAIN)
ENUM_OR_STR(ETT_SEPARATOR)
ENUM_OR_STR(ETT_REDIRECT)
ENUM_OR_STR(ETT_SPLIT)
ENUM_OR_STR(ETT_PIPE)
ENUM_OR_STR(ETT_DAEMON)
ENUM_OR_STR(ETT_COMMENT)
ENUM_OR_STR(ETT_DOUBLE_QUOTED)
ENUM_OR_STR(ETT_SINGLE_QUOTED)
ENUM_OR_STR(ETT_ERROR)

